// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADBg10NUua-Js4vp5shA5cM0wl-gw-BNY',
    appId: '1:235668946421:web:3507ac841813ab1b2034bc',
    messagingSenderId: '235668946421',
    projectId: 'qr-code-9e511',
    authDomain: 'qr-code-9e511.firebaseapp.com',
    storageBucket: 'qr-code-9e511.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQk7xMJOrCRJpzd58_IKpyTgzOQdCFGLg',
    appId: '1:235668946421:android:2669a8e2e0d00e632034bc',
    messagingSenderId: '235668946421',
    projectId: 'qr-code-9e511',
    storageBucket: 'qr-code-9e511.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2dWmgJbRyqDWTiBkJqyUvy447CGkwHi0',
    appId: '1:235668946421:ios:790b2b8b07d5eee92034bc',
    messagingSenderId: '235668946421',
    projectId: 'qr-code-9e511',
    storageBucket: 'qr-code-9e511.appspot.com',
    iosBundleId: 'com.example.qrCode',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2dWmgJbRyqDWTiBkJqyUvy447CGkwHi0',
    appId: '1:235668946421:ios:ceb3ad7b294332ab2034bc',
    messagingSenderId: '235668946421',
    projectId: 'qr-code-9e511',
    storageBucket: 'qr-code-9e511.appspot.com',
    iosBundleId: 'com.example.qrCode.RunnerTests',
  );
}
